- hosts: es01, es02
  become: yes
  handlers:
    - name: reload elasticsearch
      systemd: name=elasticsearch state=restarted
  pre_tasks:
    - name: Set variable for environment
      include_vars: variables.yml
      tags: always
    - name: Upgrade RedHat
      yum: name='@^Infrastructure Server' state=present
  roles:
    - { role: ansible-oracle-java,
        java_version: 8,
        java_subversion: 92,
        java_set_javahome: true,
        tags: java
      }
  tasks:
    - block:
        - name: Set ulimit
          lineinfile: dest=/etc/security/limits.conf regexp="^(.*)soft(.*)nofile(.*)$" line="*   soft   nofile    64000"

        - name: Set ulimit
          lineinfile: dest=/etc/security/limits.conf regexp="^(.*)hard(.*)nofile(.*)$" line="*   hard   nofile    64000"

        - name: Set HEAP SIZE
          lineinfile: dest=/etc/environment regexp="^ES_HEAP_SIZE" line='ES_HEAP_SIZE="1024m"'
      tags: install

    - name: Check if elasticsearch is installed
      yum: list=elasticsearch
      register: yum_check

    - block:
      - get_url: url=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.rpm dest=/tmp
      - yum: name=/tmp/elasticsearch-5.4.0.rpm
      - systemd: name=elasticsearch state=started enabled=yes
      - wait_for: port=9200 delay=20
      - command: /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack
      when: yum_check.results.0 is not defined

    - template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
      notify: reload elasticsearch

    - script: files/elasticsearch_config.sh
      tags: config

- hosts: es03
  become: yes
  handlers:
      - name: reload nginx
        docker_container:
          name: nginx-head
          state: started
          restart: yes
  pre_tasks:
    - name: Set variable for environment
      include_vars: variables.yml
      tags: always
    - name: Upgrade RedHat
      yum: name='@^Infrastructure Server' state=present
  roles:
    - { role: ansible-role-docker,
        tags: docker
      }
  tasks:
      - yum: name=docker-python state=present

      - systemd: name=docker state=started enabled=yes

      - file: path=/opt/elasticsearch-head state=directory

      - template: src=elasticsearch_head_nginx.conf.j2 dest=/opt/elasticsearch-head/nginx.conf
        notify: reload nginx

      - name: Create a elasticsearch-head container
        docker_container:
          name: elasticsearch-head
          image: mobz/elasticsearch-head:5
          restart_policy: always

      - name: Create a nginx container
        docker_container:
          name: nginx-head
          image: h3nrik/nginx-ldap
          links:
            - "elasticsearch-head:elasticsearch-head"
          volumes:
            - /opt/elasticsearch-head/nginx.conf:/nginx.conf:ro
          ports:
            - 9100:80
          restart_policy: always
